### ISSUE TITLE
The driver does not compile on systems with kernel version 6.x

### ISSUE THREAD

**Issue by hcdeeken** [ardangelo/sharp-drm-driver#11]
I am trying to set up my beepy with Arch Linux ARM, using the files from https://github.com/DelusionalLogic/beepy-packages
The PKGBUILD file pulls in the git repository, so I am using the current source.

When the system tries build the module, I get two compile time errors (see attached make.log)

The first points to a function which was available with kernel 5.x, but seems to be removed with later versions.
I found this as a indication: https://www.spinics.net/lists/dri-devel/msg374191.html
Arch Linux ARM for Raspberry Pi comes out of the box with kernel 6.6.14

The second just needs another include file (drm/drm_fbdev_generic.h).

I know that Arch Linux is probably out of scope here, but sooner or later Raspbian will get newer kernels, so this is more or less future proofing ;)

[sharp-drm-make.log](https://github.com/ardangelo/sharp-drm-driver/files/14167545/sharp-drm-make.log)

**Comment by hcdeeken** [comment]
Ah, I forgot to mention: this has worked in the past, some time ago. I sadly can't remember when exactly and which kernel and driver version it was.

**Comment by hcdeeken** [comment]
Ok, Kernel version 6.1 seems to work, but at least starting with 6.4 it fails. No idea about 6.2 or 6.3  yet

**Comment by ih8ms** [comment]
Same here. Kernel 6.4 or even 6.6 (current Armbian 24.2) would be highly appreciated.

**Comment by markatlnk** [comment]
I made the mistake of doing an apt update so now I am stuck without a working display or keyboard.  Is someone looking at this?  Don't think I have the time to chase it all down.

**Comment by ardangelo** [comment]
Sorry I missed these comments, I've pushed updates for both the display and keyboard drivers for Linux 6.6. Please let me know if you have any issues with the updates.
