### ISSUE TITLE
Not building on current Raspberry Pi OS version (10-10-23)

### ISSUE THREAD

**Issue by KGOrphanides** [ardangelo/sharp-drm-driver#6]
Neither the sharp-drm driver nor its companion keyboard driver build on the Raspberry Pi OS Lite 32-bit image from the Raspberry Pi Imager, dated October 10th 2023 (https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2023-10-10/2023-10-10-raspios-bookworm-armhf-lite.img.xz).

[bash-log.txt](https://github.com/ardangelo/sharp-drm-driver/files/13308186/bash-log.txt)
[sharp-drm-make.log](https://github.com/ardangelo/sharp-drm-driver/files/13308187/sharp-drm-make.log)

I've also detailed the issue in an issue raised on the documentation at
https://github.com/sqfmi/beepy-docs/issues/21

And added keyboard driver make logs this issue at
https://github.com/ardangelo/beepberry-keyboard-driver/issues/4

**Comment by ardangelo** [comment]
Thanks for the detailed reports. I updated the packages to support changes in Debian 12, and they are working for me on both Debian 11 and 12 now. Please let me know if you are seeing any more problems.

**Comment by KGOrphanides** [comment]
Confirmed working. Thank you for the fast response.
